version: '2.0'
services:
  web:
    build: .
    ports:
    - "1313:1313"
    volumes:
    - ./:/site
    command: sh -c "hugo && hugo server --disableFastRender --buildDrafts --watch --bind 0.0.0.0"
